/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatePinIdRouteImport } from './routes/template.$pinId'
import { Route as AuthMagicLinkConfirmRouteImport } from './routes/auth/magic-link/confirm'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatePinIdRoute = TemplatePinIdRouteImport.update({
  id: '/template/$pinId',
  path: '/template/$pinId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicLinkConfirmRoute = AuthMagicLinkConfirmRouteImport.update({
  id: '/auth/magic-link/confirm',
  path: '/auth/magic-link/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/brand-kit': typeof BrandKitRoute
  '/settings': typeof SettingsRoute
  '/template/$pinId': typeof TemplatePinIdRoute
  '/auth/magic-link/confirm': typeof AuthMagicLinkConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/brand-kit': typeof BrandKitRoute
  '/settings': typeof SettingsRoute
  '/template/$pinId': typeof TemplatePinIdRoute
  '/auth/magic-link/confirm': typeof AuthMagicLinkConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/brand-kit': typeof BrandKitRoute
  '/settings': typeof SettingsRoute
  '/template/$pinId': typeof TemplatePinIdRoute
  '/auth/magic-link/confirm': typeof AuthMagicLinkConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/brand-kit'
    | '/settings'
    | '/template/$pinId'
    | '/auth/magic-link/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/brand-kit'
    | '/settings'
    | '/template/$pinId'
    | '/auth/magic-link/confirm'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/brand-kit'
    | '/settings'
    | '/template/$pinId'
    | '/auth/magic-link/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  BrandKitRoute: typeof BrandKitRoute
  SettingsRoute: typeof SettingsRoute
  TemplatePinIdRoute: typeof TemplatePinIdRoute
  AuthMagicLinkConfirmRoute: typeof AuthMagicLinkConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$pinId': {
      id: '/template/$pinId'
      path: '/template/$pinId'
      fullPath: '/template/$pinId'
      preLoaderRoute: typeof TemplatePinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic-link/confirm': {
      id: '/auth/magic-link/confirm'
      path: '/auth/magic-link/confirm'
      fullPath: '/auth/magic-link/confirm'
      preLoaderRoute: typeof AuthMagicLinkConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  BrandKitRoute: BrandKitRoute,
  SettingsRoute: SettingsRoute,
  TemplatePinIdRoute: TemplatePinIdRoute,
  AuthMagicLinkConfirmRoute: AuthMagicLinkConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
