/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PinPinIdRouteImport } from './routes/pin.$pinId'
import { Route as AuthMagicLinkConfirmRouteImport } from './routes/auth/magic-link/confirm'

const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PinPinIdRoute = PinPinIdRouteImport.update({
  id: '/pin/$pinId',
  path: '/pin/$pinId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicLinkConfirmRoute = AuthMagicLinkConfirmRouteImport.update({
  id: '/auth/magic-link/confirm',
  path: '/auth/magic-link/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/pin/$pinId': typeof PinPinIdRoute
  '/auth/magic-link/confirm': typeof AuthMagicLinkConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/pin/$pinId': typeof PinPinIdRoute
  '/auth/magic-link/confirm': typeof AuthMagicLinkConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/pin/$pinId': typeof PinPinIdRoute
  '/auth/magic-link/confirm': typeof AuthMagicLinkConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boards' | '/pin/$pinId' | '/auth/magic-link/confirm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boards' | '/pin/$pinId' | '/auth/magic-link/confirm'
  id: '__root__' | '/' | '/boards' | '/pin/$pinId' | '/auth/magic-link/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  PinPinIdRoute: typeof PinPinIdRoute
  AuthMagicLinkConfirmRoute: typeof AuthMagicLinkConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin/$pinId': {
      id: '/pin/$pinId'
      path: '/pin/$pinId'
      fullPath: '/pin/$pinId'
      preLoaderRoute: typeof PinPinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic-link/confirm': {
      id: '/auth/magic-link/confirm'
      path: '/auth/magic-link/confirm'
      fullPath: '/auth/magic-link/confirm'
      preLoaderRoute: typeof AuthMagicLinkConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  PinPinIdRoute: PinPinIdRoute,
  AuthMagicLinkConfirmRoute: AuthMagicLinkConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
